{% set name = "cryptominisat" %}
{% set version = "5.6.5" %}
{% set sha256 = "b2751f8380a59c4885bea4c297536f0af2230306b1458d3e6b78d6e29f37b9d2" %}

package:
  name: pycryptosat
  version: {{ version }}

source:
  url: https://github.com/msoos/cryptominisat/archive/{{ commit }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - setuptools
    - zlib
  run:
    - python
    - zlib

test:
  imports:
    - pycryptosat
  commands:
    - conda inspect linkages -p $PREFIX pycryptosat  # [not win]
    - conda inspect objects -p $PREFIX pycryptosat  # [osx]
    - echo -e '1 0\n-1 0' | cryptominisat5_simple | grep UNSATISFIABLE
    - echo -e '1 0\n1 -1 0' | cryptominisat5_simple | grep SATISFIABLE

about:
  home: https://github.com/msoos/cryptominisat
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An advanced SAT Solver https://www.msoos.org
  description: An advanced SAT Solver https://www.msoos.org
  dev_url: https://github.com/msoos/cryptominisat

extra:
  recipe-maintainers:
    - gshiba
    - msoos
    - saraedum
