{% set name = "cryptominisat" %}
{% set version = "5.11.20" %}
{% set sha256 = "82f0fae7e8469dfe84c5804fa0fb02bd054977f59e2f444057ee81cb85cea738" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/msoos/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Use-CFLAGS.patch
    - 0002-remove-sysroot.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('cryptominisat', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make   # [linux]
  host:
    - python
    - setuptools <60
    - libboost-devel
    - libsqlite
    - zlib
  run:
    - python

test:
  imports:
    - pycryptosat
  commands:
    - echo -e '1 0\n-1 0' | cryptominisat5 | grep UNSATISFIABLE
    - echo -e '1 0\n1 -1 0' | cryptominisat5 | grep SATISFIABLE

about:
  home: https://github.com/msoos/cryptominisat
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An advanced SAT Solver https://www.msoos.org
  description: An advanced SAT Solver https://www.msoos.org
  dev_url: https://github.com/msoos/cryptominisat

extra:
  recipe-maintainers:
    - gshiba
    - msoos
    - saraedum
