{% set name = "cryptominisat" %}
{% set version = "5.12.1" %}
{% set sha256 = "fa504ae5846c80a3650fda620383def7f3d1d9d5d08824b57e13c4d41e881d89" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/msoos/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('cryptominisat', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make   # [linux]
  host:
    - python
    - setuptools <60
    - libboost-devel
    - libsqlite
    - zlib
  run:
    - python

test:
  imports:
    - pycryptosat
  commands:
    - echo -e '1 0\n-1 0' | cryptominisat5 | grep UNSATISFIABLE
    - echo -e '1 0\n1 -1 0' | cryptominisat5 | grep SATISFIABLE

about:
  home: https://github.com/msoos/cryptominisat
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An advanced SAT Solver https://www.msoos.org
  description: An advanced SAT Solver https://www.msoos.org
  dev_url: https://github.com/msoos/cryptominisat

extra:
  recipe-maintainers:
    - gshiba
    - msoos
    - saraedum
