{% set name = "cryptominisat" %}
{% set version = "5.8.0" %}
{% set sha256 = "50153025c8503ef32f32fff847ee24871bb0fc1f0b13e17fe01aa762923f6d94" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/msoos/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - 0001-Use-CFLAGS.patch

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_compatible('cryptominisat', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
  host:
    - python
    - setuptools
    - boost-cpp
    - zlib
  run:
    - python
    - boost-cpp
    - zlib

test:
  imports:
    - pycryptosat
  commands:
    - echo -e '1 0\n-1 0' | cryptominisat5 | grep UNSATISFIABLE
    - echo -e '1 0\n1 -1 0' | cryptominisat5 | grep SATISFIABLE

about:
  home: https://github.com/msoos/cryptominisat
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An advanced SAT Solver https://www.msoos.org
  description: An advanced SAT Solver https://www.msoos.org
  dev_url: https://github.com/msoos/cryptominisat

extra:
  recipe-maintainers:
    - gshiba
    - msoos
    - saraedum
