{% set name = "cryptominisat" %}
{% set version = "5.11.4" %}
{% set sha256 = "abeecb29a73e8566ae6e9afd229ec991d95b138985565b2378af95ef1ce1d317" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/msoos/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_compatible('cryptominisat', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make   # [unix]
  host:
    - python
    - setuptools
    - boost-cpp
    - zlib
  run:
    - python
    - boost-cpp
    - zlib

test:
  imports:
    - pycryptosat
  commands:
    - echo -e '1 0\n-1 0' | cryptominisat5 | grep UNSATISFIABLE
    - echo -e '1 0\n1 -1 0' | cryptominisat5 | grep SATISFIABLE

about:
  home: https://github.com/msoos/cryptominisat
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: An advanced SAT Solver https://www.msoos.org
  description: An advanced SAT Solver https://www.msoos.org
  dev_url: https://github.com/msoos/cryptominisat

extra:
  recipe-maintainers:
    - gshiba
    - msoos
    - saraedum
